[package]
name = "symm"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Simple symlink manager"
homepage = "https://github.com/tednaaa/symm"
repository = "https://github.com/tednaaa/symm"
readme = "README.md"
keywords = ["symlink", "manager", "cli"]

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
dirs = "6.0.0"
toml = "0.8.22"
