[package]
name = "symm"
version = "0.1.0"
edition = "2021"
description = "Simple symlink manager"
license = "MIT"
repository = "https://github.com/tednaaa/symm"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
dirs = "6.0.0"
toml = "0.8.22"
